### ISSUE TITLE
Relay access denied: ./bin/buildout seems to try and fail to send an email upon first run

### ISSUE THREAD

**Issue by chaoflow** [eestec/eestec.portal#46]
```
2013-04-09 18:44:14 INFO IMPORTING _type=eestec.portal.lc, _path=lc/rivendell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/cfl/.cache/buildout/eggs/collective.recipe.plonesite-1.8.1-py2.7.egg/collective/recipe/plonesite/plonesite.py", line 269, in <module>
    main(app, parser)  # FIXME: undefined name 'app'
  File "/home/cfl/.cache/buildout/eggs/collective.recipe.plonesite-1.8.1-py2.7.egg/collective/recipe/plonesite/plonesite.py", line 209, in main
    runProfiles(portal, profiles_initial)
  File "/home/cfl/.cache/buildout/eggs/collective.recipe.plonesite-1.8.1-py2.7.egg/collective/recipe/plonesite/plonesite.py", line 50, in runProfiles
    stool.runAllImportStepsFromProfile(profile)
  File "/home/cfl/.cache/buildout/eggs/Products.GenericSetup-1.7.3-py2.7.egg/Products/GenericSetup/tool.py", line 350, in runAllImportStepsFromProfile
    ignore_dependencies=ignore_dependencies)
  File "/home/cfl/.cache/buildout/eggs/Products.GenericSetup-1.7.3-py2.7.egg/Products/GenericSetup/tool.py", line 1100, in _runImportStepsFromContext
    message = self._doRunImportStep(step, context)
  File "/home/cfl/.cache/buildout/eggs/Products.GenericSetup-1.7.3-py2.7.egg/Products/GenericSetup/tool.py", line 1015, in _doRunImportStep
    return handler(context)
  File "/home/cfl/dev/eestec/eestec.portal/src/quintagroup.transmogrifier/quintagroup/transmogrifier/exportimport.py", line 135, in importSiteStructure
    for item in pipeline:
  File "/home/cfl/dev/eestec/eestec.portal/src/quintagroup.transmogrifier/quintagroup/transmogrifier/logger.py", line 30, in __iter__
    for item in self.previous:
  File "/home/cfl/dev/eestec/eestec.portal/src/quintagroup.transmogrifier/quintagroup/transmogrifier/portlets.py", line 146, in __iter__
    for item in self.previous:
  File "/home/cfl/dev/eestec/eestec.portal/src/quintagroup.transmogrifier/quintagroup/transmogrifier/comments.py", line 115, in __iter__
    for item in self.previous:
  File "/home/cfl/dev/eestec/eestec.portal/src/quintagroup.transmogrifier/quintagroup/transmogrifier/propertymanager.py", line 228, in __iter__
    for item in self.previous:
  File "/home/cfl/dev/eestec/eestec.portal/src/quintagroup.transmogrifier/quintagroup/transmogrifier/references.py", line 21, in __iter__
    for item in self.previous:
  File "/home/cfl/dev/eestec/eestec.portal/src/quintagroup.transmogrifier/quintagroup/transmogrifier/marshall.py", line 92, in __iter__
    for item in self.previous:
  File "/home/cfl/dev/eestec/eestec.portal/src/quintagroup.transmogrifier/quintagroup/transmogrifier/binary.py", line 167, in __iter__
    for item in self.previous:
  File "/home/cfl/dev/eestec/eestec.portal/src/quintagroup.transmogrifier/quintagroup/transmogrifier/datacorrector.py", line 36, in __iter__
    for item in self.previous:
  File "/home/cfl/.cache/buildout/eggs/collective.transmogrifier-1.3-py2.7.egg/collective/transmogrifier/sections/constructor.py", line 55, in __iter__
    obj = fti._constructInstance(context, id)
  File "/home/cfl/.cache/buildout/eggs/Products.CMFCore-2.2.7-py2.7.egg/Products/CMFCore/TypesTool.py", line 568, in _constructInstance
    notify(ObjectCreatedEvent(obj))
  File "/home/cfl/.cache/buildout/eggs/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/home/cfl/.cache/buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/home/cfl/.cache/buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/home/cfl/.cache/buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/home/cfl/.cache/buildout/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/home/cfl/.cache/buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 32, in objectEventNotify
    zope.component.subscribers((event.object, event), None)
  File "/home/cfl/.cache/buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/home/cfl/.cache/buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/home/cfl/.cache/buildout/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/home/cfl/dev/eestec/eestec.portal/src/eestec/portal/content/event.py", line 42, in event_created
    emails.event.created_notify_board(context)
  File "/home/cfl/dev/eestec/eestec.portal/src/eestec/portal/emails/event.py", line 71, in created_notify_board
    body=body % body_values)
  File "/home/cfl/.cache/buildout/eggs/plone.api-0.1b1-py2.7.egg/plone/api/portal.py", line 138, in send_email
    immediate=True
  File "/home/cfl/.cache/buildout/eggs/Products.MailHost-2.13.1-py2.7.egg/Products/MailHost/MailHost.py", line 237, in send
    self._send(mfrom, mto, messageText, immediate)
  File "/home/cfl/.cache/buildout/eggs/Products.MailHost-2.13.1-py2.7.egg/Products/MailHost/MailHost.py", line 337, in _send
    self._makeMailer().send(mfrom, mto, messageText)
  File "/home/cfl/.cache/buildout/eggs/Products.CMFPlone-4.2.2-py2.7.egg/Products/CMFPlone/patches/sendmail.py", line 12, in _catch
    return func(*args, **kwargs)
  File "/home/cfl/.cache/buildout/eggs/zope.sendmail-3.7.5-py2.7.egg/zope/sendmail/mailer.py", line 77, in send
    connection.sendmail(fromaddr, toaddrs, message)
  File "/nix/store/yzj6p5f7iyh247pwxrg97y3klm6d0cni-python-2.7.3/lib/python2.7/smtplib.py", line 733, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'board@eestec.net': (554, '5.7.1 <board@eestec.net>: Relay access denied')}
```

**Comment by balkian** [comment]
What config are you using in buildout? Is it in the master branch or the nixosprofile one?

Offtopic: glad to see you around, playing with the site :beers:

**Comment by chaoflow** [comment]
Fernando Sánchez notifications@github.com writes:

> What config are you using in buildout? Is it in the master branch or
> the nixosprofile one?

I was on the nixprofile branch, but that shouldn't make a difference.

If you use master and start with a fresh repo, i.e. no var, i.e. no
plone instance yet, you should see the same error. The error does not
appear the second time you run buildout.

## 

Florian Friesdorf flo@chaoflow.net
  GPG FPR: 7A13 5EEE 1421 9FC2 108D  BAAF 38F8 99A3 0C45 F083
Jabber/XMPP: flo@chaoflow.net
IRC: chaoflow on freenode,ircnet,blafasel,OFTC
